apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog
spec:
  replicas: 1
  strategy: {}
  template:
    spec:
      containers:
        - image: quay.io/adrina/coolstore-catalog:main-1490639be647bb4d6e283e0d9f4b29c6e6b1949b
          imagePullPolicy: Always
          name: catalog
          ports:
            - containerPort: 8080
          resources: {}
      serviceAccountName: default
status: {}
