apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog
  labels:
    app.openshift.io/runtime: spring-boot
  annotations:
    app.openshift.io/connects-to: '[{"apiVersion":"apps/v1","kind":"Deployment","name":"catalog-database"}]'
    app.openshift.io/vcs-ref: main
    app.openshift.io/vcs-uri: https://github.com/adnan-drina/coolstore-catalog.git
spec:
  replicas: 1
  strategy: {}
  template:
    spec:
      containers:
        - name: catalog
          image: >-
            quay.io/adrina/coolstore-catalog:main-f690c400f814c3e9d39b380fe39d465cc546a9ce
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8443
              protocol: TCP
            - containerPort: 8778
              protocol: TCP
          readinessProbe:
            failureThreshold: 15
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          env:
          - name: JAVA_OPTS_APPEND
            value: -Dspring.profiles.active=openshift
          volumeMounts:
          - name: application-config
            mountPath: "/deployments/config"
            readOnly: true
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      volumes:
        - name: application-config
          configMap:
            name: catalog-spring-config
            items:
            - key: application.yaml
              path: application.yaml
      serviceAccountName: default
status: {}
