apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  name: catalog
  namespace: coolstore-catalog-stage
spec:
  port:
    targetPort: http
  to:
    kind: Service
    name: catalog
    weight: 100
  wildcardPolicy: None
