kind: ConfigMap
apiVersion: v1
metadata:
  name: catalog-spring-config
  namespace: coolstore-catalog-stage
data:
  application.yaml: |-
    server:
      port: 8080
    spring:
      config:
        activate:
          on-profile: openshift
      datasource:
        url: 'jdbc:postgresql://catalog-database:5432/catalog'
        username: catalog
        password: mysecretpassword
        initialize: 'true'
        initialization-mode: always
        schema: 'classpath:/schema.sql'
        continue-on-error: 'true'
    inventory:
      url: 'inventory.coolstore-inventory-stage.svc.cluster.local'
    management:
      metrics:
        export:
          prometheus:
            enabled: 'true'
        endpoints:
          web:
            exposure:
              include: 'info,health,metrics,prometheus'
    feign:
      hystrix:
        enabled: 'true'
    hystrix:
      command:
        default:
          execution:
            isolation:
              thread:
                timeoutInMilliseconds: 20000