apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  name: coolstore-catalog
  namespace: coolstore-catalog-dev
spec:
  port:
    targetPort: http
  to:
    kind: Service
    name: coolstore-catalog
    weight: 100
  wildcardPolicy: None
