apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  creationTimestamp: null
  name: coolstore-catalog-binding
  namespace: coolstore-catalog-cicd
spec:
  params:
  - name: imageRepo
    value: quay.io/adrina/coolstore-catalog
  - name: tlsVerify
    value: "true"
status: {}
