apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  creationTimestamp: null
  name: coolstore-catalog-binding
  namespace: coolstore-catalog-cicd
spec:
  params:
  - name: imageRepo
    value: quay.io/adrina/coolstore-catalog
  - name: tlsVerify
    value: "true"
  - name: argoApp
    value: coolstore-catalog-cicd-app
  - name: environmentConfig
    value: environments/coolstore-catalog-stage/apps/app-coolstore-catalog/services/coolstore-catalog/base/config/
status: {}
