apiVersion: v1
kind: ConfigMap
metadata:
  name: maven-settings
  namespace: coolstore-catalog-cicd
data:
  settings.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <settings>
      <profiles>
        <profile>
          <id>nexus</id>
          <!--Enable snapshots for the built in central repo to direct -->
          <!--all requests to nexus via the mirror -->
          <repositories>
            <repository>
              <id>central</id>
              <url>http://central</url>
              <releases>
                <enabled>true</enabled>
              </releases>
              <snapshots>
                <enabled>true</enabled>
              </snapshots>
            </repository>
          </repositories>
          <pluginRepositories>
            <pluginRepository>
              <id>central</id>
              <url>http://central</url>
              <releases>
                <enabled>true</enabled>
              </releases>
              <snapshots>
                <enabled>true</enabled>
              </snapshots>
            </pluginRepository>
          </pluginRepositories>
          <properties>
              <altDeploymentRepository>nexus::http://nexus.nexus-repository.svc.cluster.local:8081/repository/maven-releases/</altDeploymentRepository>
              <altReleaseDeploymentRepository>nexus::http://nexus.nexus-repository.svc.cluster.local:8081/repository/maven-releases/</altReleaseDeploymentRepository>
              <altSnapshotDeploymentRepository>nexus::http://nexus.nexus-repository.svc.cluster.local:8081/repository/maven-snapshots/</altSnapshotDeploymentRepository>
          </properties>
        </profile>
        <profile>
          <id>sonar</id>
          <activation>
              <activeByDefault>true</activeByDefault>
          </activation>
          <properties>
              <sonar.host.url>https://sonarqube-sonarqube.apps.cluster-5ded.5ded.example.opentlc.com</sonar.host.url>
              <sonar.login>admin</sonar.login>
              <sonar.password>admin123</sonar.password>
          </properties>
        </profile>
      </profiles>
      <activeProfiles>
        <activeProfile>nexus</activeProfile>
      </activeProfiles>
      <servers>
        <server>
          <id>nexus</id>
          <username>admin</username>
          <password>admin123</password>
        </server>
      </servers>
      <mirrors>
        <mirror>
          <id>nexus</id>
          <name>nexus</name>
          <url>http://nexus.nexus-repository.svc.cluster.local:8081/repository/maven-public/</url>
          <mirrorOf>*</mirrorOf>
        </mirror>
      </mirrors>
    </settings>