apiVersion: v1
data:
  database-name: Y2F0YWxvZw==
  database-password: bXlzZWNyZXRwYXNzd29yZA==
  database-user: Y2F0YWxvZw==
kind: Secret
metadata:
  annotations:
    template.openshift.io/expose-database_name: '{.data[''database-name'']}'
    template.openshift.io/expose-password: '{.data[''database-password'']}'
    template.openshift.io/expose-username: '{.data[''database-user'']}'
  labels:
    template: postgresql-ephemeral-template
  name: catalog-database
  namespace: coolstore-catalog-dev
type: Opaque
