bases:
- ./config

commonLabels:
  app.kubernetes.io/name: catalog
  app.kubernetes.io/part-of: coolstore-catalog
  app.openshift.io/runtime: spring

commonAnnotations:
  app.openshift.io/connects-to: >-
    ["catalog-database",{"apiVersion":"apps.openshift.io/v1","kind":"Deployment","name":"catalog-database"}]
  app.openshift.io/vcs-ref: main
  app.openshift.io/vcs-uri: https://github.com/adnan-drina/coolstore-catalog.git