kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: coolstore-catalog-source-pvc
  namespace: coolstore-catalog-cicd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp2
  volumeMode: Filesystem